import { readFileSync, writeFileSync } from "node:fs";
import { format, resolveConfig } from "prettier";
const out = "docs/gameplay analysis Sep 2026/scoring-progression-results.html";
const data = JSON.parse(readFileSync("operator-results/scoring-study-20260915/progression/analysis.json", "utf8"));
const fmt = (n) => n.toLocaleString("en-US");
const signed = (n) => (n > 0 ? "+" : "") + fmt(n);
const strict = data.tiers[3];
const tierNames = ["Wave + mode", "+ captured build", "+ exact loadout", "+ starting defenses / meta"];
const exRows = [
  ["Total wave points", "score"],
  ["Combat points", "combat"],
  ["Explicit bonuses", "bonuses"],
  ["Burj HP lost", "burjLoss"],
  ["Buildings lost", "buildingLoss"],
  ["Launcher HP lost", "launcherLoss"],
  ["Defense sites lost", "siteLoss"],
  ["Starting combo", "comboStart"],
  ["Manual shots", "shots"],
  ["Manual kills", "manualKills"],
  ["Upgrade kills", "upgradeKills"],
];
const examples = data.examples
  .map(
    (p, i) =>
      `<article class="example"><div class="tag">Example ${i + 1} · wave ${p.wave} · ${p.betterRow.build}</div><h3>${p.scoreDelta < 0 ? "Better protection, fewer points" : p.combatDelta < 0 ? "The building bonus reverses the result" : "Protection and points align"}</h3><p>Same starting defenses and owned nodes: <strong>${p.betterRow.owned.join(", ") || "none"}</strong>. Starting Burj ${p.betterRow.assets.burj} HP; ${p.betterRow.assets.buildings.filter(Boolean).length} buildings alive; launcher HP ${p.betterRow.assets.launchers.join(" / ")}.</p><div class="table-wrap"><table><thead><tr><th>Measure</th><th>${p.better} · fewer losses</th><th>${p.worse} · more losses</th></tr></thead><tbody>${exRows.map(([name, key]) => `<tr><td>${name}</td><td>${fmt(p.betterRow[key])}</td><td>${fmt(p.worseRow[key])}</td></tr>`).join("")}<tr><td>Combat duration</td><td>${p.betterRow.duration.toFixed(2)} s</td><td>${p.worseRow.duration.toFixed(2)} s</td></tr></tbody></table></div><p>Better-protected run: <strong>${signed(p.scoreDelta)} total points</strong>, ${signed(p.combatDelta)} combat points. ${p.scoreDelta < 0 ? "It lost no assets yet earned less. Its starting combo was ×4 versus ×10, and it encountered a different battle. This is a score/protection disagreement, not proof that good shooting caused a lower score." : p.combatDelta < 0 ? "An extra 100 building-survival points outweigh a 56-point combat deficit. Here the explicit bonus connects protection to reward." : "The cleaner defense also earned more combat points. Different seeds and inherited combo prevent a controlled attribution to shooting alone."}</p><details><summary>Source breakdown and active use</summary><div class="table-wrap"><table><thead><tr><th>Source</th><th>${p.better}: base / uplift / multi</th><th>${p.worse}: base / uplift / multi</th></tr></thead><tbody>${[
        ...new Set([...Object.keys(p.betterRow.sources), ...Object.keys(p.worseRow.sources)]),
      ]
        .map(
          (source) =>
            `<tr><td>${source}</td>${[p.betterRow, p.worseRow]
              .map((r) => {
                const s = r.sources[source] ?? { base: 0, uplift: 0, multi: 0 };
                return `<td>${fmt(s.base)} / ${fmt(s.uplift)} / ${fmt(s.multi)}</td>`;
              })
              .join("")}</tr>`,
        )
        .join(
          "",
        )}</tbody></table></div><p>EMP/F-15 casts: ${p.betterRow.activeUses.length} versus ${p.worseRow.activeUses.length}. No active-use comparison can be inferred from this pair.</p></details></article>`,
  )
  .join("");
const publicRows = data.rows.map((r) =>
  Object.fromEntries(Object.entries(r).filter(([k]) => !["seedHash", "encounterHash"].includes(k))),
);
const publicData = {
  progression: data.progression,
  runRows: data.runRows,
  tiers: data.tiers,
  throughWave: data.throughWave,
  rows: publicRows,
};
const html = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Does better protection earn more? · Part four</title><style>
:root{color-scheme:dark;--text:#edf4fc;--muted:#aabbd0;--line:#30425a;--panel:#142136;--green:#64dcc7;--amber:#edc47e;--red:#ef999b}*{box-sizing:border-box}body{margin:0;background:#0a1321;color:var(--text);font:16px/1.55 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:48px 25px 80px}h1{font-size:clamp(35px,5vw,59px);line-height:1.1;letter-spacing:-.035em;margin:14px 0 24px}h2{font-size:25px;margin:0 0 15px}h3{font-size:21px}.lede{font-size:21px;color:var(--muted);max-width:900px}.tag{color:var(--green);font-size:12px;letter-spacing:.12em;text-transform:uppercase}.muted,small{color:var(--muted)}section{padding:25px;margin-top:30px;background:var(--panel);border:1px solid var(--line);border-radius:13px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:27px}.card{padding:20px;border:1px solid var(--line);border-radius:10px}.big{display:block;font-size:38px;font-weight:750;letter-spacing:-.04em}.columns{display:grid;grid-template-columns:1fr 1fr;gap:26px}.callout{border-left:3px solid var(--amber);padding:9px 16px;background:#202d41}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px 8px;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}th:first-child,td:first-child{text-align:left}th{color:var(--muted);font-weight:500}td.heat{background:#20433f;color:#c1fff0}select{font:inherit;background:#091321;color:inherit;border:1px solid #627994;padding:8px;border-radius:6px;max-width:100%}.toolbar{display:flex;gap:18px;flex-wrap:wrap;margin:20px 0}label{display:flex;gap:8px;align-items:center;flex-wrap:wrap}svg{width:100%;height:auto;display:block}svg text{fill:var(--muted);font:12px system-ui}.legend{font-size:13px;color:var(--muted)}.stack{height:26px;background:#26364a;display:flex;border-radius:5px;overflow:hidden}.example{border-top:1px solid var(--line);padding:24px 0}.example:last-child{padding-bottom:0}details{margin:16px 0}summary,a{color:var(--green)}summary{cursor:pointer}li{margin:10px 0}.proof{font-variant-numeric:tabular-nums;font-size:14px}@media(max-width:640px){main{padding:25px 13px 50px}.cards,.columns{grid-template-columns:1fr}.card{padding:14px 18px}.big{font-size:31px}section{padding:20px 14px}.lede{font-size:18px}h2{font-size:23px}}
</style></head><body><main><div class="tag">Gameplay analysis · Part four · 16 September 2026</div><h1>Progression is clear.<br>The protection signal is limited.</h1><p class="lede">Final score strongly tracks how far a run gets. Once we ask whether better protection earns more under comparable conditions, usable evidence narrows to a small set of early-wave comparisons.</p><div class="cards"><div class="card"><span class="big">0.953</span>score / final-wave correlation<br><small>Pearson; 26 runs</small></div><div class="card"><span class="big">41 / 168</span>completed-wave records have a strict peer<br><small>Same wave, build, loadout and starting defenses</small></div><div class="card"><span class="big">0</span>strict matches after wave four<br><small>No clean late-wave comparison in this corpus</small></div></div>
<section><h2>What this answers</h2><ul><li><strong>Progression is a strong predictor of final score.</strong> A simple final-wave line fits 90.9% of score variation here; leave-one-run-out predictive R² is 87.9%. This is not a causal allocation of score to survival versus skill.</li><li><strong>Some early-wave evidence favors cleaner defense.</strong> In 11 of 12 strict pairs with unambiguously different loss outcomes, the better-protected run earns more. But all 12 are waves one–two, share runs, and retain different seeds and starting combos.</li><li><strong>Protection and score can disagree.</strong> One matched wave-two run loses no assets yet earns 704 fewer points than a peer losing two Burj HP. Starting combo and encounter differences remain plausible explanations.</li><li><strong>The late-wave question remains open.</strong> These recordings do not isolate shooting, build quality or active timing at the reported difficulty wall. No wave-11 recording exists.</li></ul><p class="callout">Keep score as a mixed outcome measure for now. This study does not validate it as a ranking of defensive quality, and does not justify choosing a replacement scoring formula.</p></section>
<section><h2>How much does progression predict?</h2><div id="progressionPlot"></div><p class="legend">Dots: individual recordings. Dashed line: the simple final-wave fit across the observed range, not a forecast. Hover or focus a dot for its run label.</p><p>Spearman rank correlation: <strong>0.981</strong>. The linear model is deliberately simple and can predict negative values at the low-wave end. Its high R² describes the broad ordering, not precise early-run predictions.</p><details><summary>Residuals from the progression baseline</summary><p class="muted">A positive residual means more points than this line predicts at that final wave. It is not a skill score: terminal-wave duration, upgrades, bonuses and earlier history still differ. These rows stay in anonymous run order.</p><div class="table-wrap"><table><thead><tr><th>Run</th><th>Final wave</th><th>Actual score</th><th>Predicted score</th><th>Residual</th></tr></thead><tbody id="residuals"></tbody></table></div></details></section>
<section><h2>Matching removes most of the late-wave evidence</h2><p class="muted">Only groups with at least two distinct recordings count. A record is one completed wave in one run; records from the same run are not independent.</p><div class="table-wrap"><table><thead><tr><th>Match requirement</th><th>Groups</th><th>Records</th><th>Runs</th>${Array.from({ length: 9 }, (_, i) => "<th>W" + (i + 1) + "</th>").join("")}</tr></thead><tbody>${data.tiers.map((t, i) => `<tr><td>${tierNames[i]}</td><td>${t.groups}</td><td>${t.rows}</td><td>${t.runs}</td>${t.byWave.map((w) => `<td class="${w.rows ? "heat" : ""}">${w.rows || "—"}</td>`).join("")}</tr>`).join("")}</tbody></table></div><p>Strict matching uses exact starting Burj HP, per-launcher HP, surviving buildings/sites and meta-progression, in addition to build and owned upgrade nodes. All 26 seeds differ. Commander state, encounter sequence, starting combo and cumulative run history are not held fixed.</p><p>Of the <strong>111</strong> strict within-group pairs, <strong>99 have identical measured losses</strong>. The remaining <strong>12</strong> involve losses in only <strong>${strict.worseOutcomeRuns}</strong> distinct worse-outcome runs. No strict loss-differing pair contains an EMP/F-15 cast.</p></section>
<section><h2>Does cleaner defense receive more?</h2><div class="toolbar"><label>Match <select id="tier">${tierNames.map((name, i) => `<option value="${i}" ${i === 3 ? "selected" : ""}>Tier ${i + 1}: ${name}</option>`).join("")}</select></label><label>Outcome <select id="outcome"><option value="burjLoss">Burj HP lost</option><option value="buildingLoss">Buildings destroyed</option><option value="launcherLoss">Launcher HP lost</option><option value="siteLoss">Defense sites destroyed</option><option value="shotSuccess">Shot damage success — context only</option></select></label><label>Points <select id="reward"><option value="score">Total wave points</option><option value="combat">Combat points, bonuses removed</option></select></label></div><p id="association"></p><div id="matchedPlot"></div><p class="muted">Each axis subtracts the matching group's mean, so this plots differences among peers rather than raw differences between waves. For asset loss, a negative correlation means more points accompany fewer losses. Shot success has the opposite desirable sign and is not an independent skill grade.</p><p id="sensitivity" class="proof"></p><p id="support" class="muted"></p><h3>Pairs where one defense is unambiguously cleaner</h3><p class="muted">“Better protected” means no greater loss on any of Burj HP, buildings, launcher HP or sites, and less loss on at least one. Mixed trade-offs and exact loss ties are excluded here; no composite asset score is invented.</p><div id="pairBar" class="stack"></div><p id="pairText"></p><details><summary>All asset associations for this tier</summary><div class="table-wrap"><table><thead><tr><th>Outcome</th><th>Total-point r</th><th>Combat-point r</th><th>Runs with nonzero outcome</th></tr></thead><tbody id="allAssociations"></tbody></table></div></details><p class="callout">The 11/12 count is not a success probability. Pairs share recordings, and almost all strict pairs tie on losses. Sparse damage variation also makes some resampled correlations undefined; the valid-draw count is shown.</p></section>
<section><h2>Stop the score counter at the same completed wave</h2><p class="muted">Cumulative earnings and cumulative Burj HP lost through that wave. Terminal partial-wave earnings are excluded. This view aligns progress, but still mixes builds, loadouts and encounter histories.</p><label>Through wave <select id="through">${data.throughWave.map((w) => `<option value="${w.wave}" ${w.wave === 4 ? "selected" : ""}>${w.wave} · ${w.runs} runs</option>`).join("")}</select></label><p id="throughText"></p><div id="throughPlot"></div><details><summary>All same-progress cumulative summaries</summary><div class="table-wrap"><table><thead><tr><th>Through wave</th><th>Runs</th><th>Score range</th><th>Total-score / Burj-loss r</th><th>Combat / Burj-loss r</th></tr></thead><tbody>${data.throughWave.map((w) => `<tr><td>${w.wave}</td><td>${w.runs}</td><td>${fmt(w.min)}–${fmt(w.max)}</td><td>${w.scoreVsBurjLoss?.toFixed(3) ?? "—"}</td><td>${w.combatVsBurjLoss?.toFixed(3) ?? "—"}</td></tr>`).join("")}</tbody></table></div><p class="muted">Wave nine has only five surviving runs. Its large correlation is not a general late-wave result. These survivors also omit runs that failed earlier.</p></details></section>
<section><h2>Three concrete strict-match examples</h2><p class="muted">Chosen to expose agreement, disagreement and the bonus contribution—not representative prevalence. Original scoring and gameplay remain untouched.</p>${examples}</section>
<section><h2>What evidence would settle the remaining question?</h2><ul><li>Late-wave attempts starting from the same encounter, loadout, asset health and combo, with the player responding to that encounter. Historical shot coordinates cannot fairly stand in for a player reacting to changed spawns.</li><li>Enough repetitions with different protection outcomes to distinguish timing/aiming effects from seed and build effects.</li><li>Separate accounting for observed asset damage, shooting, upgrade kills and active use. A target being intercepted low is still not proof that the manual shot saved it.</li></ul><p>Part four is complete as an observational analysis. It identifies the available signal and the missing comparisons. No new experiment, scoring change or part-five rescoring has been run.</p></section>
<section><h2>Verification and limits</h2><p class="proof">26 context replays match recorded checkpoints, exact final ticks, action consumption and maintained stored-summary comparisons. 168 completed-wave rows + 26 terminal rows reconcile to the prior event ledger and final scores. Wave-start/end balances match completed-wave earnings.</p><p class="proof">13 statistical checks cover correlation/ties, linear fit, leave-one-out prediction, within-group centering, partial-order comparisons and quantiles. An independent Python calculation agrees on the progression fit, matching coverage and all 40 stratified associations. Strict examples pass exact matching and loss-order assertions.</p><details><summary>Uncertainty, terminology and reproduction</summary><p>Within-group correlations center both score and outcome separately within each tier's matching groups. Run-block resampling draws whole runs with replacement, preserving their waves together; one thousand draws use seed 16092026. Groups need at least two distinct original runs in each resample. Undefined correlations are omitted and valid counts reported. The 2.5–97.5 percentile range is sampling sensitivity for this small one-player corpus, not a population skill confidence interval. Leave-one-run-out ranges remove a whole recording at a time.</p><p>Asset-loss counts omit harmless arrivals, invulnerability-blocked hits and hypothetical future threats. The building bonus mechanically favors surviving buildings; total and combat-only results are therefore shown separately. Shot success shares kill outcomes with score and is not an independent assessment of skill. Nine clip labels are too sparse and their individual-action scope too uncertain to assign to entire waves.</p><p>Source files and reproduction: <a href="scoring-progression-method.md">part-four method</a>. Private contexts, full data, pair lists and check results remain under <code>operator-results/scoring-study-20260915/progression/</code>. This report embeds anonymous aggregate/row results, not raw recordings or capture identifiers.</p></details><p><a href="README.md">All reports</a> · <a href="scoring-quality-results.html">Part three</a> · <a href="scoring-quality-review.html">Local score-hidden clips</a></p></section>
<script id="data" type="application/json">${JSON.stringify(publicData).replace(/</g, "\u003c")}</script><script>
const D=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-US'),num=n=>n===null?'not estimable':n.toFixed(3);
const names={burjLoss:'Burj HP lost',buildingLoss:'Buildings destroyed',launcherLoss:'Launcher HP lost',siteLoss:'Defense sites destroyed',shotSuccess:'Shot damage success'};
function escapeText(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function plot(id,points,xlabel,ylabel,line=null){const W=920,H=365,L=76,R=25,T=20,B=65;let xs=points.map(p=>p.x),ys=points.map(p=>p.y);if(line)ys.push(...line.map(p=>p.y));let xmin=Math.min(0,...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(...ys);if(xmax===xmin)xmax=xmin+1;if(ymax===ymin)ymax=ymin+1;const px=x=>L+(x-xmin)/(xmax-xmin)*(W-L-R),py=y=>H-B-(y-ymin)/(ymax-ymin)*(H-T-B);let s='<svg viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+escapeText(xlabel+' versus '+ylabel)+'">';
for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;s+='<line x1="'+px(x)+'" y1="'+T+'" x2="'+px(x)+'" y2="'+(H-B)+'" stroke="#263a51"/><line x1="'+L+'" y1="'+py(y)+'" x2="'+(W-R)+'" y2="'+py(y)+'" stroke="#263a51"/><text x="'+px(x)+'" y="'+(H-B+22)+'" text-anchor="middle">'+Number(x.toFixed(2)).toLocaleString()+'</text><text x="'+(L-10)+'" y="'+(py(y)+4)+'" text-anchor="end">'+Number(y.toFixed(0)).toLocaleString()+'</text>';}
if(line)s+='<path d="M '+line.map(p=>px(p.x)+' '+py(p.y)).join(' L ')+'" fill="none" stroke="#edc47e" stroke-width="2" stroke-dasharray="6 5"/>';
for(const p of points)s+='<circle tabindex="0" aria-label="'+escapeText(p.label)+'" cx="'+px(p.x)+'" cy="'+py(p.y)+'" r="5" fill="#64dcc7" opacity=".78"><title>'+escapeText(p.label)+'</title></circle>';s+='<text x="'+((L+W-R)/2)+'" y="'+(H-14)+'" text-anchor="middle">'+escapeText(xlabel)+'</text><text x="'+L+'" y="14">'+escapeText(ylabel)+'</text></svg>';
$(id).innerHTML=s;}
const fit=D.progression,minWave=Math.min(...D.runRows.map(r=>r.finalWave)),maxWave=Math.max(...D.runRows.map(r=>r.finalWave));plot('progressionPlot',D.runRows.map(r=>({x:r.finalWave,y:r.score,label:r.label+': wave '+r.finalWave+', '+fmt(r.score)+' points'})),'Final wave','Final score',[minWave,maxWave].map(x=>({x,y:fit.intercept+fit.slope*x})));
$('residuals').innerHTML=D.runRows.map(r=>{const e=fit.estimates.find(e=>e.label===r.label);return '<tr><td>'+r.label+'</td><td>'+r.finalWave+'</td><td>'+fmt(r.score)+'</td><td>'+fmt(Math.round(e.predicted))+'</td><td>'+fmt(Math.round(e.residual))+'</td></tr>';}).join('');
function key(r,t){const a=[r.wave,r.mode];if(t>=1)a.push(r.build);if(t>=2)a.push(r.owned);if(t>=3)a.push(r.assets);return JSON.stringify(a);}
function render(){const ti=Number($('tier').value),t=D.tiers[ti],out=$('outcome').value,reward=$('reward').value,a=t.associations.find(a=>a.outcome===out&&a.reward===reward);$('association').textContent=names[out]+' versus '+(reward==='score'?'total':'combat-only')+' points: within-group r = '+num(a.r)+'. '+a.rows+' records from '+a.runs+' runs in '+a.groups+' matching groups.';
const groups=new Map();for(const r of D.rows.filter(r=>r[out]!==null)){const k=key(r,ti);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r);}const points=[];for(const g of groups.values()){if(g.length<2)continue;const mx=g.reduce((n,r)=>n+r[out],0)/g.length,my=g.reduce((n,r)=>n+r[reward],0)/g.length;for(const r of g)points.push({x:r[out]-mx,y:r[reward]-my,label:r.label+' wave '+r.wave+': '+names[out]+' '+r[out]+', '+fmt(r[reward])+' points'});}plot('matchedPlot',points,'Outcome difference from group mean','Point difference from group mean');
$('sensitivity').textContent='Run-resampling range: '+(a.runResamplingRange?a.runResamplingRange.map(num).join(' to '):'not estimable')+' ('+a.bootstrapValid+'/1,000 valid draws). Leave-one-run-out: '+(a.leaveOneRunOut?a.leaveOneRunOut.map(num).join(' to '):'not estimable')+'.';$('support').textContent=a.varyingGroups+' groups contain outcome variation; '+a.nonzeroOutcomeRuns+' runs have a nonzero outcome in matched records. A single damage-bearing run cannot establish a dependable relationship.';
const p=reward==='score'?t.totalScore:t.combatScore,n=t.comparablePairs;$('pairBar').innerHTML=[['higher','#64dcc7'],['tied','#edc47e'],['lower','#ef999b']].map(([k,c])=>'<span style="width:'+100*p[k]/(n||1)+'%;background:'+c+'" title="'+p[k]+' '+k+'"></span>').join('');$('pairText').textContent='Better-protected run earns more in '+p.higher+', equal points in '+p.tied+', fewer in '+p.lower+' of '+n+' comparable pairs. '+t.lossTies+' loss ties and '+t.mixedOutcomes+' mixed outcomes excluded. Informative waves: '+t.informativeWaves.join(', ')+'.';$('allAssociations').innerHTML=Object.keys(names).map(k=>{const x=t.associations.find(a=>a.outcome===k&&a.reward==='score'),y=t.associations.find(a=>a.outcome===k&&a.reward==='combat');return '<tr><td>'+names[k]+'</td><td>'+num(x.r)+'</td><td>'+num(y.r)+'</td><td>'+x.nonzeroOutcomeRuns+'</td></tr>';}).join('');}
function through(){const w=D.throughWave.find(w=>w.wave===Number($('through').value));$('throughText').textContent=w.runs+' runs reached this completed boundary. Cumulative score '+fmt(w.min)+'–'+fmt(w.max)+'. Score / cumulative Burj-loss r = '+num(w.scoreVsBurjLoss)+'; combat-only r = '+num(w.combatVsBurjLoss)+'.';plot('throughPlot',w.points.map(p=>({x:p.burjLoss,y:p.score,label:p.label+': '+p.burjLoss+' Burj HP lost, '+fmt(p.score)+' points'})),'Cumulative Burj HP lost','Cumulative score');}
for(const id of ['tier','outcome','reward'])$(id).addEventListener('change',render);$('through').addEventListener('change',through);render();through();
</script></main></body></html>`;
writeFileSync(out, await format(html, { ...(await resolveConfig(out)), parser: "html" }));
console.log("Wrote " + out);
