import { readFileSync, writeFileSync } from "node:fs";
import { format, resolveConfig } from "prettier";
const root = "operator-results/scoring-study-20260915/quality/";
const data = JSON.parse(readFileSync(root + "shooting-metrics.json", "utf8"));
const notes = JSON.parse(readFileSync("docs/gameplay analysis Sep 2026/scoring-quality-judgments.json", "utf8"));
const s = data.pooled;
const fmt = (n) => n.toLocaleString("en-US");
const pct = (a, b) => ((100 * a) / b).toFixed(1) + "%";
const sum = (a, f) => a.reduce((n, e) => n + f(e), 0);
const waves = data.runs.flatMap((r) => r.waves);
const exposure = Object.fromEntries(
  [
    "combatTicks",
    "threatPresentTicks",
    "emptyChargeThreatTicks",
    "readyThreatNoFireTicks",
    "existingBlastCoverageTicks",
  ].map((k) => [k, sum(waves, (w) => w[k])]),
);
const damage = Object.fromEntries(
  ["burj", "buildings", "launcherHP", "sites"].map((k) => [k, sum(waves, (w) => w.damage[k])]),
);
const safe = data.windows.filter((w) => w.upgradeKills > 0 && w.loss === 0);
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What counts as good shooting? · Part three</title><style>
:root{color-scheme:dark;--muted:#acbdd0;--green:#62dcca;--amber:#efc480;--pink:#e9a19d;--line:#30425b}*{box-sizing:border-box}body{margin:0;background:#0a1321;color:#edf3fb;font:16px/1.55 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:44px 24px 70px}h1{font-size:clamp(34px,5vw,57px);line-height:1.08;letter-spacing:-.035em;margin:16px 0}h2{font-size:24px;margin-top:0}h3{font-size:18px}.lede{font-size:21px;color:var(--muted);max-width:880px}.tag{font-size:12px;letter-spacing:.12em;color:var(--green);text-transform:uppercase}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card,section{border:1px solid var(--line);border-radius:12px;background:#152236;padding:24px}.card strong{display:block;font-size:36px;letter-spacing:-.04em}section{margin-top:28px}.muted,small{color:var(--muted)}a{color:var(--green)}.callout{border-left:3px solid var(--amber);padding:8px 16px;background:#202b3d}.stack{display:flex;height:30px;overflow:hidden;border-radius:6px;background:#29364a}.legend{display:flex;gap:18px;flex-wrap:wrap;margin:14px 0;font-size:14px}.dot{display:inline-block;width:10px;height:10px;margin-right:6px;border-radius:3px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:right;padding:10px 8px;border-bottom:1px solid var(--line);white-space:nowrap}td:first-child,th:first-child{text-align:left}th{color:var(--muted);font-weight:500}select{font:inherit;padding:8px;background:#0a1321;color:inherit;border:1px solid #647890;border-radius:6px;max-width:100%}.columns{display:grid;grid-template-columns:1fr 1fr;gap:26px}.metric-row{display:grid;grid-template-columns:100px 1fr 62px;gap:12px;align-items:center;margin:12px 0}.metric-row .stack{height:20px}.key{font-size:26px;font-weight:700}summary{cursor:pointer;color:var(--green)}li{margin:10px 0}.note{border-top:1px solid var(--line);padding:14px 0}.pill{display:inline-block;border:1px solid var(--amber);border-radius:6px;padding:5px 10px;color:var(--amber)}@media(max-width:620px){main{padding:26px 13px 45px}.cards,.columns{grid-template-columns:1fr}.card{padding:16px}.card strong{font-size:31px}section{padding:20px 15px}.lede{font-size:18px}.metric-row{grid-template-columns:80px 1fr 52px;gap:7px;font-size:13px}}
</style></head><body><main><div class="tag">Replay study · Part three · 15 September 2026</div><h1>An empty shot is an outcome.<br>Was it a bad choice?</h1><p class="lede">${pct(s.contestedEmpty, s.resolved - s.successful)} of resolved empty shots had an intended target killed by another source first. That makes raw shot success an incomplete measure of good play.</p><p class="pill">Measurements verified · human calibration pending</p><p><a href="scoring-quality-review.html">Watch the ten score-hidden clips →</a> Start with clips <strong>01, 03 and 05</strong> before opening the provisional judgments below. Clip playback requires the local Vite server and private study corpus; this aggregate report is self-contained.</p>
<div class="cards"><div class="card"><strong>${pct(s.successful, s.resolved)}</strong>resolved shots caused damage<br><small>${fmt(s.successful)} / ${fmt(s.resolved)}</small></div><div class="card"><strong>${fmt(s.contestedEmpty)}</strong>empty shots with a competing kill<br><small>${fmt(s.contestedEmptyUpgrade)} involved upgrade systems</small></div><div class="card"><strong>${fmt(safe.length)}</strong>withholding intervals with upgrade kills and no asset damage<br><small>At least one second; charge and threats present</small></div></div>
<section><h2>What we can say now</h2><ul><li><strong>Manual shots are frequently productive.</strong> ${fmt(s.allKills)} manual-origin kills came from ${fmt(s.shots)} shots, including chain descendants. A shot can hit several threats.</li><li><strong>Empty shots have different histories.</strong> Some lose intended targets to other defenses or another manual shot. Others begin with no intended target because the player is aiming ahead.</li><li><strong>Withholding is sometimes followed by a good local outcome.</strong> Existing defenses can remove threats while the player has firing capacity available. Observing that outcome does not establish the player's intent.</li><li><strong>We still need your judgment.</strong> These describe shooting behavior and outcomes. They are not a validated skill score or a ranking of your runs.</li></ul></section>
<section><h2>Shot outcomes, with the denominator exposed</h2><p><label for="run">Recording </label><select id="run"><option value="all">All 26 recordings</option></select></p><p id="denominator"></p><div id="distribution"></div><p id="rates"></p><div class="columns"><div><h3>Repeated and contested coverage</h3><p id="coverage"></p></div><div><h3>Projected urgent interceptions</h3><p id="urgent"></p><p class="muted">The current-course predictor ignores defenses and structural shadowing. A projected impact within 60 ticks is <strong>not a proved save</strong>. EMP slow-motion also changes wall-clock timing.</p></div></div><p class="callout">“Intended target” is the reference captured by the game's firing function. It is not a mind-reading device: <strong>${fmt(s.productiveNoIntended)}</strong> resolved kill-producing shots had no intended target at launch.</p><details><summary>Why the resolution count differs from part two</summary><p>Part two used root combo-resolution events to identify empty shots. Part three observes projectile and entire descendant-explosion lifetime. It resolves ${fmt(s.resolved)} shots normally and leaves ${s.terminalUnresolved} unresolved at recording end; ${s.boundaryCleared} were boundary-cleared. The 57 additional resolved empty shots were previously in the “no logged resolved outcome” group. This refines shot-outcome accounting; reward attribution and all original totals are unchanged.</p></details></section>
<section><h2>Outcomes through waves</h2><p class="muted">Pooled descriptive counts, including partial terminal waves. Later waves involve different threat volume, loadouts and surviving runs. These figures do not establish deteriorating aim or a capacity wall.</p><div class="table-wrap"><table><thead><tr><th>Wave</th><th>Run segments</th><th>Resolved shots</th><th>Damage success</th><th>Kills / shot</th><th>Burj HP lost</th></tr></thead><tbody>${Array.from(
  { length: 10 },
  (_, i) => {
    const ws = waves.filter((w) => w.wave === i + 1);
    const n = sum(ws, (w) => w.resolved);
    return `<tr><td>${i + 1}</td><td>${ws.length}</td><td>${fmt(n)}</td><td>${pct(
      sum(ws, (w) => w.successful),
      n,
    )}</td><td>${(sum(ws, (w) => w.resolvedKills) / n).toFixed(2)}</td><td>${sum(ws, (w) => w.damage.burj)}</td></tr>`;
  },
).join("")}</tbody></table></div></section>
<section><h2>Opportunity is context, not a penalty for waiting</h2><div class="columns"><div><p><span class="key">${pct(exposure.emptyChargeThreatTicks, exposure.threatPresentTicks)}</span><br>of active threat-present ticks had no ready firing charge.</p><p class="muted">${fmt(exposure.emptyChargeThreatTicks)} / ${fmt(exposure.threatPresentTicks)} ticks. This mixes reloading and launcher availability; it does not prove unavoidable overload.</p></div><div><p><span class="key">${fmt(data.windows.length)}</span><br>intervals lasted at least one second with threats and a ready charge, without manual fire.</p><p class="muted">${fmt(safe.length)} included upgrade kills with no observed asset loss during the interval. In-flight manual shots and prior damage can still matter.</p></div></div><p>Observed asset losses across the corpus: ${damage.burj} Burj HP, ${damage.buildings} buildings, ${damage.launcherHP} launcher HP and ${damage.sites} defense sites. These are separate loss counts, not a composite quality score.</p><details><summary>Opportunity measurement limits</summary><p>Availability is projected on a cloned charge state before each recorded action tick, preserving simulation state. We exclude shops, wave-complete intervals and post-destruction animation. A threat being present does not establish a viable or useful aim point; an upgrade being owned does not prove a lane was covered. Withholding windows are outcome-selected examples, not evidence that all non-shooting time was wise.</p></details></section>
<section><h2>Calibrate the judgment</h2><p>The clip player uses original recorded actions and the Pixi battlefield renderer, with score/combo/reward labels hidden and recorded taps marked. The focal choice starts near 2 seconds. Playback, pause, replay and scrubbing are available.</p><p>Please label <strong>01, 03 and 05</strong>: <em>Productive, Wasteful, Sensible withholding, or Ambiguous</em>, with a short reason. Labels save in your browser; copy them into the conversation.</p><p><a href="scoring-quality-review.html">Open clip review →</a></p><details><summary>Provisional agent judgments — spoilers</summary><p class="muted">${notes.reviewMethod} No candidate rankings have been computed.</p>${notes.judgments.map((j) => `<div class="note"><strong>${j.clip} · ${j.judgment}</strong> · ${j.confidence} confidence · ${j.time}<p>${j.observation}</p><p class="muted">${j.interpretation}</p></div>`).join("")}</details></section>
<section><h2>Verification and next boundary</h2><p>26 stored summaries match; all actions and 3,159 checkpoints consumed; 4,819 full sanitized state/RNG samples match the part-two baseline. Six additional controlled cases cover full shot lifetime, boundary/terminal censoring, shared intended targets, competing kills, read-only recharge projection and asset-loss observation.</p><p>Ten clips: 60 exact seek-frame checks and 70 rendered/headless checkpoint matches. Play/pause, label persistence and 390px layout passed with no page errors. Six temporal frames per clip were visually inspected; your motion/choice judgments remain essential.</p><p class="muted">One player's 26 runs across eight builds, ending on waves 2–10. No independent skill labels yet, no run ranking, no score correlation test, no counterfactual saves, no scoring or spawn change. Part four's matched progression comparisons come after this calibration.</p><p><a href="scoring-quality-method.md">Definitions and selection rules</a> · <a href="scoring-attribution-results.html">Part two attribution</a></p></section>
<script id="metrics" type="application/json">${JSON.stringify({ pooled: s, runs: data.runs.map(({ label, ...r }) => ({ label, ...Object.fromEntries(Object.entries(r).filter(([k]) => !["waves", "windows"].includes(k))) })) }).replace(/</g, "\\u003c")}</script><script>
const data=JSON.parse(document.getElementById('metrics').textContent);const $=id=>document.getElementById(id);const fmt=n=>n.toLocaleString('en-US');for(const r of data.runs){const o=document.createElement('option');o.value=r.label;o.textContent=r.label;$('run').append(o);}function render(){const s=data.runs.find(r=>r.label===$('run').value)||data.pooled;$('denominator').textContent=fmt(s.shots)+' fired = '+fmt(s.resolved)+' normally resolved + '+s.boundaryCleared+' boundary-cleared + '+s.terminalUnresolved+' terminal-unresolved. Only resolved shots enter the rates below.';const max=Math.max(...s.distribution);$('distribution').innerHTML=s.distribution.map((n,i)=>'<div class="metric-row"><span>'+['0 kills','1 kill','2 kills','3 kills','4+ kills'][i]+'</span><div class="stack"><span style="width:'+100*n/(max||1)+'%;background:'+(i?'#62dcca':'#e9a19d')+'"></span></div><span>'+fmt(n)+'</span></div>').join('');$('rates').textContent=(100*s.successful/s.resolved).toFixed(1)+'% damage success · '+(s.resolvedKills/s.resolved).toFixed(2)+' kills per resolved shot · '+(s.resolvedBase/s.resolved).toFixed(2)+' base threat value per resolved shot. Base value uses existing game weights, excluding combo and bonuses.';$('coverage').textContent=fmt(s.repeatedCoverage)+' of '+fmt(s.shots)+' shots shared an intended target with another live manual interceptor. '+fmt(s.contestedEmpty)+' resolved empty shots had a competing kill, including '+fmt(s.contestedEmptyUpgrade)+' involving upgrades. These are observations, not automatically wasted shots.';$('urgent').textContent=fmt(s.urgentKills)+' manual-origin kills occurred when the maintained predictor put the threat within 60 ticks of damaging the Burj on its current course.';}$('run').addEventListener('change',render);render();
</script></main></body></html>`;
writeFileSync(
  "docs/gameplay analysis Sep 2026/scoring-quality-results.html",
  await format(html, {
    ...(await resolveConfig("docs/gameplay analysis Sep 2026/scoring-quality-results.html")),
    parser: "html",
  }),
);
console.log("Wrote part-three report; human label gate remains open.");
