import { readFileSync, writeFileSync } from "node:fs";
import { format, resolveConfig } from "prettier";
const data = JSON.parse(readFileSync("operator-results/scoring-study-20260915/attribution/aggregate.json", "utf8"));
const html = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Where the points come from · Dubai Missile Command</title>
<style>
:root{color-scheme:dark;--bg:#0a1220;--panel:#131f30;--text:#edf3fb;--muted:#aabbd0;--line:#2c3d54;--manual:#54d6c0;--upgrade:#9eacff;--bonus:#ecc378;--impact:#ef9384}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:16px/1.55 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:54px 28px 80px}h1{font-size:clamp(34px,5vw,62px);line-height:1.08;letter-spacing:-.04em;margin:15px 0 24px;max-width:850px}h2{font-size:25px;margin:0 0 14px}h3{font-size:17px;margin:0 0 10px}p{margin:12px 0}.eyebrow{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--manual)}.lede{font-size:21px;max-width:850px;color:var(--muted)}section{margin-top:34px;padding:25px;background:var(--panel);border:1px solid var(--line);border-radius:14px}.muted,small{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:28px}.card{padding:20px;border:1px solid var(--line);border-radius:12px}.big{display:block;font-size:36px;font-weight:750;letter-spacing:-.04em}.toolbar{display:flex;gap:20px;align-items:center;flex-wrap:wrap;margin:22px 0}select,button{font:inherit;color:var(--text);background:var(--bg);border:1px solid #61758e;border-radius:6px;padding:8px;max-width:100%}label{display:flex;gap:9px;align-items:center;flex-wrap:wrap}.legend{display:flex;flex-wrap:wrap;gap:16px;font-size:13px;margin:14px 0}.dot{display:inline-block;width:10px;height:10px;border-radius:3px;margin-right:6px}.stack{display:flex;width:100%;height:28px;border-radius:5px;overflow:hidden;background:#263247}.seg{height:100%;min-width:0}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.flow>div{padding:18px;border:1px solid var(--line);border-top:3px solid var(--manual);border-radius:8px}.flow strong{display:block}.flow span{color:var(--muted);font-size:14px}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px 8px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}th:first-child,td:first-child{text-align:left}th{color:var(--muted);font-weight:500}.wave-row{display:grid;grid-template-columns:110px 1fr 92px;align-items:center;gap:12px;margin:13px 0;font-size:14px}.wave-row .stack{height:22px}.wave-row small{display:block;font-size:11px}.notice{border-left:3px solid var(--bonus);padding-left:16px}.columns{display:grid;grid-template-columns:1fr 1fr;gap:28px}a{color:var(--manual)}summary{cursor:pointer;color:var(--manual)}li{margin:8px 0}.proof{font-variant-numeric:tabular-nums}footer{margin-top:25px;color:var(--muted);font-size:13px}@media(max-width:600px){main{padding:28px 14px 48px}section{padding:18px 14px}.cards,.columns,.flow{grid-template-columns:1fr}.cards{gap:10px}.card{padding:13px 16px}.big{font-size:30px}.wave-row{grid-template-columns:68px 1fr 64px;gap:8px;font-size:12px}.lede{font-size:18px}h2{font-size:22px}}
</style></head><body><main>
<div class="eyebrow">Reward attribution · Study point two · 15 September 2026</div>
<h1>Score rewards survival,<br>then shares the multiplier.</h1>
<p class="lede">Across 26 recordings, explicit bonuses supply <strong>47.8%</strong> of final score. Manual shots and their chains receive <strong>28.5%</strong>. Upgrade systems receive <strong>22.6%</strong>, and impact effects receive <strong>1.1%</strong>.</p>
<p class="muted">These are observed reward origins. They do not measure how much score would disappear without your shooting, upgrade choices or active timing.</p>
<div class="cards"><div class="card"><span class="big">1,663,424</span>points reconciled exactly</div><div class="card"><span class="big">376,472</span>kill points added by combo</div><div class="card"><span class="big">33 / 345</span>multi-shot credits came from flares</div></div>
<section><h2>How credit travels</h2><div class="flow"><div><strong>1 · Origin</strong><span>Manual shot, upgrade system or impact creates a damaging effect.</span></div><div><strong>2 · Kill + chain</strong><span>Final blow owns the kill. Descendants retain their initiating source, even after the root expires.</span></div><div><strong>3 · Shared combo</strong><span>The current global multiplier boosts every kill source. Manual and flare roots can raise or reset it.</span></div><div><strong>4 · Other awards</strong><span>Root multi-kill awards and wave/building bonuses add points separately.</span></div></div><p class="notice">An automated kill can benefit from a combo built by manual shots. Assigning that uplift to its final kill source is accounting, not a causal claim about player skill.</p></section>
<section><h2>Follow the points</h2><p class="muted">Select a recording, then compare its reward composition and waves. Terminal waves remain included in run totals.</p><div class="toolbar"><label>Recording <select id="run"><option value="all">All 26 recordings</option></select></label><label><input id="normalize" type="checkbox"> Equal-width wave bars</label></div><div id="totals" class="proof"></div><div id="legend" class="legend"></div><div id="scorebar" class="stack" role="img"></div><div class="table-wrap"><table><thead><tr><th>Reward origin</th><th>Base kill</th><th>Combo uplift</th><th>Multi-kill</th><th>Total</th><th>Kills</th></tr></thead><tbody id="sources"></tbody></table></div><p class="muted"><small>Upgrade systems include player-triggered EMP/F-15 and flare effects; the label does not imply zero player agency. Impact includes explosions caused by enemy impacts and Burj damage effects. Phalanx has no scored kills in this corpus.</small></p><h3 style="margin-top:26px">Where earnings accumulate by wave</h3><div id="waves"></div><p class="muted"><small>In the pooled view, bars sum runs reaching each wave; sample counts and terminal counts are shown. Later waves represent fewer surviving runs. Equal-width bars compare composition, not earnings.</small></p></section>
<section><h2>The multiplier crosses ownership boundaries</h2><div class="columns"><div><h3>What raised or reset combo?</h3><div class="table-wrap"><table><thead><tr><th>Root origin</th><th>Raised</th><th>Lowered</th><th>Unchanged</th></tr></thead><tbody id="combos"></tbody></table></div><p class="muted"><small>Unchanged includes a successful root at ×10 or an empty root already at ×1. These are resolved-root events, not a count of individual kills.</small></p></div><div><h3>Who received its extra points?</h3><p id="uplift"></p><p class="muted">The report separates base kill value from uplift. It does not assign each later multiplier point to an earlier shot or flare: their effects overlap through the shared combo state.</p></div></div></section>
<section><h2>Shots, kills and the awkward counters</h2><div id="shots"></div><p class="notice">The game's <code>playerCaused</code> flag includes flare explosions. Treating it as “manual shot” would count flare multi-kills and combo changes as shooting performance.</p><p id="neutral"></p><p class="muted">No kills had damaging contributors from different sources in these recordings; the observer's assist case was verified separately. “Kill-producing shot” uses observed final kills, including chains. It does not estimate a save or an avoided future hit.</p></section>
<section><h2>What this establishes</h2><ul><li>Final score combines shooting, upgrade-system kills and survival bonuses. It is not a pure shooting measure.</li><li>Manual and flare roots affect a multiplier that also rewards the other systems. Final-blow ownership alone misses that relationship.</li><li>Multi-kill awards belong to several sources, including enemy-impact explosions. The game's multi-shot counter is narrower, but still includes flare roots.</li><li>Score attribution cannot answer whether late waves leave meaningful timing decisions. That remains a separate opportunity/pressure study.</li></ul><p class="muted">The earlier 53.2% bonus share used completed-wave earnings only. This report's 47.8% uses complete run totals, including terminal-wave earnings. Both describe the same corpus with different denominators.</p></section>
<section><h2>Verification and limits</h2><p class="proof">26 / 26 stored summaries match · 3,159 recorded checkpoints consumed and verified · 4,819 identical baseline/observed state samples · 172,247 replay ticks · 11 controlled cases pass</p><details><summary>Method, reproduction and limitations</summary><ul><li>Gameplay source files were transformed only in memory for an analysis bundle. No game rules, reward values, RNG calls or action ordering were changed. Exact-count source replacements and AST insertions are recorded in the local instrumentation inventory.</li><li>Both bundles expose identical read-only replay-consumption metadata. Full sanitized replay-anchor state, including Sets/Maps, RNG state and action/checkpoint consumption, is hashed every 120 ticks, at recorded checkpoint ticks, and at observed state/shop/bonus boundaries. This is sampled equivalence, not an every-tick full-state comparison.</li><li>Reward sums, destroyed counts, fired shots and multi-shot counters reconcile per wave and per run. All actions and checkpoints are consumed, final ticks are exact, and maintained recap comparison matches stored summaries.</li><li>Controlled cases cover player/system/impact chains after root removal, mixed-source damage assists, incremental multi-kill awards, actual flare turncoat payoff, unscored neutralization and successful shot identity. Source-labelled synthetic explosions test lineage; they do not independently exercise every system's firing routine.</li><li>All 26 recordings are this player's iOS draft-mode runs across eight builds, ending in Burj destruction on waves 2–10. There is no wave-11 recording, player comparison or counterfactual simulation. No paid spending or friendly-fire penalties occurred.</li><li>Sources follow real damaging calls, not distance or threat altitude. Per-cast lineage for active systems is not established. Shots without a logged resolution can include effects cleared at a boundary or still unresolved at the recording end.</li><li>Private replay payloads and detailed event logs stay under <code>operator-results/scoring-study-20260915/attribution/</code>. This HTML embeds only study labels and summarized results.</li></ul><p>Reproduce from the existing local corpus:</p><pre style="overflow:auto">node scripts/scoring-study/build.mjs
node operator-results/scoring-study-20260915/attribution/baseline.mjs
node operator-results/scoring-study-20260915/attribution/observed.mjs --cases
node operator-results/scoring-study-20260915/attribution/observed.mjs
node scripts/scoring-study/aggregate.mjs
node scripts/scoring-study/report.mjs</pre></details></section>
<footer>Point two complete: measured attribution. Scoring and spawn redesigns have not begun. <a href="gameplay-design-report.html">Earlier gameplay study →</a></footer>
<script id="data" type="application/json">__DATA__</script><script>
const data=JSON.parse(document.getElementById('data').textContent);const $=id=>document.getElementById(id);const fmt=n=>n.toLocaleString('en-US');const pct=(n,d)=>(d?100*n/d:0).toFixed(1)+'%';
const names={player:'Manual shots + chains',hornets:'Wild Hornets',roadrunner:'Roadrunner',ironBeam:'Iron Beam',phalanx:'Phalanx',patriot:'Patriot',flare:'Flare',emp:'EMP',f15:'F-15',impact:'Impact effects'};
const colors={manual:'#54d6c0',upgrade:'#9eacff',bonus:'#ecc378',impact:'#ef9384'};const total=s=>s?s.base+s.uplift+s.multi:0;
const parts=s=>[['Manual shots',total(s.sources.player),colors.manual],['Upgrade systems',Object.entries(s.sources).filter(([k])=>!['player','impact'].includes(k)).reduce((n,[,v])=>n+total(v),0),colors.upgrade],['Explicit bonuses',s.waveClear+s.buildingBonus,colors.bonus],['Impact effects',total(s.sources.impact),colors.impact]];
function bar(s,denom=s.score){return parts(s).map(([name,n,color])=>'<span class="seg" style="width:'+100*n/(denom||1)+'%;background:'+color+'" title="'+name+': '+fmt(n)+' ('+pct(n,s.score)+')"></span>').join('');}
for(const r of data.runs){const o=document.createElement('option');o.value=r.label;o.textContent=r.label+' · wave '+r.finalWave+' · '+fmt(r.score);$('run').append(o);}
$('legend').innerHTML=parts(data.pooled).map(([name,,c])=>'<span><i class="dot" style="background:'+c+'"></i>'+name+'</span>').join('');
function render(){const r=data.runs.find(r=>r.label===$('run').value);const s=r||data.pooled;$('totals').textContent=fmt(s.score)+' points · '+fmt(s.kills)+' scored kills · '+fmt(s.shots)+' manual shots';$('scorebar').innerHTML=bar(s);$('scorebar').setAttribute('aria-label',parts(s).map(([name,n])=>name+' '+pct(n,s.score)).join(', '));
$('sources').innerHTML=Object.entries(names).map(([key,name])=>{const x=s.sources[key]||{base:0,uplift:0,multi:0,kills:0};return '<tr><td>'+name+'</td>'+[x.base,x.uplift,x.multi,total(x),x.kills].map(n=>'<td>'+fmt(n)+'</td>').join('')+'</tr>';}).join('')+'<tr><td>Wave-clear bonus</td><td>—</td><td>—</td><td>—</td><td>'+fmt(s.waveClear)+'</td><td>—</td></tr><tr><td>Building-survival bonus</td><td>—</td><td>—</td><td>—</td><td>'+fmt(s.buildingBonus)+'</td><td>—</td></tr>';
const waves=r?r.waves.map(w=>({...w,n:1,term:Number(w.terminal)})):Array.from({length:10},(_,i)=>{const entries=data.runs.flatMap(r=>r.waves.filter(w=>w.wave===i+1));const x={wave:i+1,score:0,waveClear:0,buildingBonus:0,sources:{},n:entries.length,term:entries.filter(w=>w.terminal).length};for(const w of entries){for(const k of ['score','waveClear','buildingBonus'])x[k]+=w[k];for(const [key,v]of Object.entries(w.sources)){const q=x.sources[key]??={base:0,uplift:0,multi:0};for(const k of ['base','uplift','multi'])q[k]+=v[k];}}return x;}).filter(w=>w.n);
const max=Math.max(...waves.map(w=>w.score));$('waves').innerHTML=waves.map(w=>'<div class="wave-row"><span>Wave '+w.wave+'<small>'+w.n+' run'+(w.n===1?'':'s')+(w.term?' · '+w.term+' terminal':'')+'</small></span><div class="stack" role="img" aria-label="Wave '+w.wave+': '+fmt(w.score)+' points">'+bar(w,$('normalize').checked?w.score:max)+'</div><span>'+fmt(w.score)+'</span></div>').join('');
$('combos').innerHTML=['player','flare'].map(k=>{const c=s.combo[k]||{up:0,reset:0,same:0};return '<tr><td>'+(k==='player'?'Manual':'Flare')+'</td><td>'+fmt(c.up)+'</td><td>'+fmt(c.reset)+'</td><td>'+fmt(c.same)+'</td></tr>';}).join('');
$('uplift').innerHTML='<strong>'+fmt(s.uplift)+'</strong> combo-uplift points ('+pct(s.uplift,s.score)+' of score): '+fmt(s.sources.player?.uplift||0)+' on manual-origin kills and '+fmt(s.uplift-(s.sources.player?.uplift||0))+' on other origins.';
const o=s.outcomes;$('shots').innerHTML='<p><strong>'+fmt(o.kill)+' / '+fmt(s.shots)+' shots ('+pct(o.kill,s.shots)+')</strong> produced at least one scored kill; '+fmt(o.emptyResolved)+' resolved without damage, '+fmt(o.assistOnly)+' damaged threats without a final kill, '+fmt(o.unresolved)+' had no logged resolved outcome, and '+fmt(o.friendlyHit)+' hit a friendly.</p><p>Multi-shot counter: <strong>'+fmt(s.multiShots.player||0)+' manual + '+fmt(s.multiShots.flare||0)+' flare</strong>. No rejected recorded fire attempts, spending or friendly-fire penalties were observed.</p>';
$('neutral').textContent=fmt(s.neutralized)+' unscored flare neutralizations count toward destroyed statistics. Together with '+fmt(s.kills)+' scored kills, they reconcile to '+fmt(s.neutralized+s.kills)+' destroyed threats.';
}
$('run').addEventListener('change',render);$('normalize').addEventListener('change',render);render();
</script></main></body></html>`;
// Deliberately exclude private captures, raw IDs, actions, and event-level positions.
const publicData = {
  method: data.method,
  pooled: data.pooled,
  runs: data.runs.map((run) =>
    Object.fromEntries(Object.entries(run).filter(([key]) => !["purchases", "activeUses"].includes(key))),
  ),
};
writeFileSync(
  "docs/gameplay analysis Sep 2026/scoring-attribution-results.html",
  await format(html.replace("__DATA__", JSON.stringify(publicData).replace(/</g, "\\u003c")), {
    ...(await resolveConfig("docs/gameplay analysis Sep 2026/scoring-attribution-results.html")),
    parser: "html",
  }),
);
console.log("Wrote docs/gameplay analysis Sep 2026/scoring-attribution-results.html");
