import { readFileSync, writeFileSync } from "node:fs";
import { format, resolveConfig } from "prettier";
const root = "operator-results/scoring-study-20260915/rescoring/";
const d = JSON.parse(readFileSync(root + "analysis.json", "utf8"));
const proof = JSON.parse(readFileSync(root + "crosscheck.json", "utf8"));
const fmt = (n) => (n === null ? "—" : n.toLocaleString("en-US", { maximumFractionDigits: 1 }));
const name = { A: "Player-only combo", B: "Per-shot rewards", C: "Defense + contribution" };
const setting = (v) =>
  v.family === "A"
    ? `uplift × ${v.alpha}`
    : v.family === "B"
      ? `${v.productive} productive + ${v.extra} extra`
      : `cap ${v.cap * 100}% of base`;
const cells = (xs) => xs.map((x) => `<td>${x}</td>`).join("");
const table = (heads, body) =>
  `<div class="scroll"><table><thead><tr>${heads.map((x) => `<th>${x}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table></div>`;
const summary = d.summaries.filter((s) => s.reference);
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Part Five — Same defense, different points</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0a1220;color:#e3ebf5;line-height:1.6}*{box-sizing:border-box}body{margin:0}main{max-width:1120px;padding:48px 24px 80px;margin:auto}h1{font-size:clamp(36px,6vw,66px);line-height:1.08;letter-spacing:-.035em;max-width:900px}h2{font-size:27px;line-height:1.25}h3{font-size:19px}p{max-width:90ch}.tag{color:#6ee1c2;text-transform:uppercase;letter-spacing:.12em;font-size:12px}.lede{font-size:21px;color:#b5c4d8}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card,section{background:#111e30;border:1px solid #2c3e54;border-radius:12px;padding:24px;margin-top:22px}.card strong{font-size:34px;display:block}.muted,small{color:#afbed1}.callout{padding:15px 18px;border-left:3px solid #f3bc69;background:#1d2939}a,summary{color:#6ee1c2}summary{cursor:pointer}details{margin:20px 0}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;font-size:14px}th,td{text-align:right;padding:11px 12px;border-bottom:1px solid #2c3e54;white-space:nowrap}th:first-child,td:first-child{text-align:left}th{color:#aabed6}select{background:#0a1220;color:inherit;font:inherit;border:1px solid #6b839e;border-radius:5px;padding:8px;max-width:100%}.toolbar{display:flex;gap:18px;flex-wrap:wrap;margin:20px 0}label{display:flex;gap:8px;align-items:center;flex-wrap:wrap;min-width:0;max-width:100%}.bar{height:6px;background:#6ea6e6;display:block;margin-top:5px;max-width:140px}.up{color:#75dfb9}.down{color:#ffb6a5}li{margin:10px 0}.formula{font-family:ui-monospace,monospace;font-size:14px;color:#b9d2ed}@media(max-width:640px){main{padding:25px 13px 50px}.cards{grid-template-columns:1fr}.card,section{padding:18px 14px}h2{font-size:24px}.lede{font-size:18px}}
</style></head><body><main><div class="tag">Gameplay analysis · Part five · 18 September 2026</div><h1>Same defense.<br>Different points.</h1><p class="lede">Three scoring families applied to the same 26 recordings. Every shot, kill, purchase and outcome stays fixed. The experiment exposes reward incentives; it does not establish which formula measures skill.</p><div class="cards">${summary.map((s) => `<div class="card"><small>${name[s.family]}</small><strong>${((s.delta / s.original) * 100).toFixed(1)}%</strong>total points at reference setting<br><small>${s.pairs.higher}/12 strict pairs favor better protection</small></div>`).join("")}</div>
<section><h2>What changes—and what does not</h2><p>Every run loses raw points under every tested setting. These formulas remove substantial original combo rewards without replacing the old point budget. <strong>Lower totals are a scale change, not evidence of worse play.</strong> Relative ranks and same-wave comparisons below show who benefits relative to peers.</p><p>Original scoring favors the better-protected recording in 11 of 12 strict loss-differing pairs. Player-only combo keeps that count. Reference per-shot rewards and bounded contribution each favor it in 8 of 12. Those pairs share recordings and cover only waves one–two; there are no strict matches after wave four.</p><p class="callout">User clarification: survival already rewards better defense through continued play. Scoring should reward better skill. Protection comparisons below are context, not a test of which formula best measures skill; that criterion has not yet been defined well enough to select a winner.</p></section>
<section><h2>The three hypotheses</h2><p>All retain every scored kill's base value, existing wave/building survival bonuses and original debits. Automated kills include upgrades and EMP/F-15; impact-origin kills are also non-manual. No new save bonus is inferred.</p><h3>A · Player-only combo</h3><p class="formula">base + survival + manual multi-kill awards + α × manual combo uplift</p><p>Original combo timing and miss resets remain. Automation receives base only. This removes the player's ability to boost automated rewards, but a miss can still reduce future manual rewards. Settings: α = 0.5, 1, 1.5.</p><h3>B · Per-shot rewards</h3><p class="formula">base + survival + P per productive shot + M per extra kill (up to 3)</p><p>No persistent streak. Include observed chains; pay each increment at kill time, including earned kills from unresolved terminal shots. Empty or contested empty shots have no direct points or penalty. Settings (P,M): (25,50), (50,100), (100,200).</p><h3>C · Defense plus bounded contribution</h3><p class="formula">base + survival + min(manual damage credit, c × all kill base), per wave</p><p>Credit each destroyed target's base proportionally to observed applied damage. This can credit assists without requiring the last hit. Cap settings: 25%, 50%, 100% of the wave's kill base. Existing survival points reward progression/buildings; they do not comprehensively measure Burj, launcher or site protection.</p><p><strong>Accounting only:</strong> no candidate score enters the simulation or shop. Gross earnings and net after original spending/penalties are separate. This corpus has zero recorded debits, so the two agree here. Fractions remain unrounded in calculations.</p></section>
<section><h2>Who gains or loses?</h2><div class="toolbar"><label>Formula <select id="variant">${d.variants.map((v) => `<option value="${v.id}" ${v.id === "A1" ? "selected" : ""}>${name[v.family]} · ${setting(v)}${v.reference ? " · reference" : ""}</option>`).join("")}</select></label><label>View <select id="scope"><option value="all">Final run totals</option>${d.throughWave.map((w) => `<option value="${w.wave}">Through completed wave ${w.wave}</option>`).join("")}</select></label></div><p id="selection" class="callout"></p><p class="muted">Rank 1 is highest. Positive rank change means moving up within the selected cohort. Final totals include partial terminal waves; completed-wave views exclude them. These are descriptive score ranks, not skill ranks.</p>${table(["Run", "Original gross", "Candidate gross", "Point change", "Rank change"], '<tr><td colspan="5">Loading</td></tr>').replace("<tbody>", '<tbody id="runs">')}<details><summary>Selected formula: wave ledger and net balance</summary><label>Run <select id="run">${d.runs.map((r) => `<option>${r.label}</option>`).join("")}</select></label><p id="runContext"></p>${table(["Wave", "Original gross", "Base", "Survival", "Premium", "Debits", "Candidate net"], "").replace("<tbody>", '<tbody id="waves">')}</details></section>
<section><h2>Does better protection receive more?</h2><p>These are all 12 strict comparisons with fewer losses on at least one asset and no greater loss on any. Builds, wave-start loadouts and defenses match; seeds, encounters and starting combo still differ. A positive number favors the better-protected recording.</p><p id="pairSummary"></p>${table(["Better protected", "Peer", "Wave", "Original difference", "Candidate difference"], "").replace("<tbody>", '<tbody id="pairs">')}<p class="muted">Eleven of twelve is not a success rate, and eight of twelve is not a calibrated quality score. The 99 strict pairs tied on all measured losses cannot discriminate protection quality. None of these 12 comparisons isolates late-wave skill.</p></section>
<section><h2>Incentives exposed by the rules</h2>${table(
  ["Situation", "Player-only combo", "Per-shot rewards", "Bounded contribution"],
  [
    ["Empty / contested shot", "Still risks manual streak", "Zero direct reward or loss", "Zero credit"],
    [
      "Automation already covers threat",
      "Last-hit manual premium",
      "Last-hit shot bonus",
      "Manual damage premium below cap",
    ],
    [
      "Stop firing at max combo",
      "No automated multiplier benefit",
      "No streak to preserve",
      "No streak; manual premium can saturate",
    ],
    [
      "Four singles vs one 4-kill shot",
      "Depends on combo + original multi",
      "200 vs 350 bonus",
      "Same credit at equal damage",
    ],
    [
      "One 8-kill vs two 4-kill shots",
      "Depends on combo + original multi",
      "350 vs 700 bonus",
      "Same credit at equal damage",
    ],
    ["Manual damage before automated kill", "No assist premium", "No assist bonus", "Proportional credit below cap"],
  ]
    .map((r) => "<tr>" + cells(r) + "</tr>")
    .join(""),
)}<p>These are algebraic comparisons at reference settings, <strong>not altered-input replays</strong>. No shots were added or removed. The four-kill cap in B makes splitting a large cluster lucrative on paper, despite rewarding a four-kill shot over four singles. Empty spam pays nothing directly, but B supplies no score risk for speculative shots and still rewards unnecessary successful ones. Ammo and timing costs continue to matter.</p><p>C removes the last-hit discontinuity when the damage history is unchanged, but still rewards manual damage that automation might otherwise have delivered. Its reference cap saturates in <strong>${d.summaries.find((s) => s.id === "C1").saturated}/${d.checks.waves}</strong> wave records, including terminal waves. Further manual contribution then earns no extra premium at fixed total base value. That can tolerate sensible reliance on defense, but can also remove encouragement to keep contributing.</p><p>The recordings contain <strong>${d.checks.contestedEmpty}</strong> empty shots whose intended targets were killed by another source during the shot lifetime. This overlap is not proof of unfair stealing or wasted play. Observed manual assist credit on non-manual kills is <strong>${fmt(d.checks.assistCredit)}</strong>; C's proposed assist advantage is therefore supported by rule cases, not a demonstrated benefit in this corpus.</p></section>
<section><h2>The labels resist a kill-count definition of quality</h2><p>Keep the user's nine labels intact. Values below follow each selected focal shot through its whole observed lifetime, which can extend beyond the clip. Labels may describe the whole clip; they cannot safely be assigned to an entire wave or recording. C's column is pre-cap damage credit, not a uniquely allocatable capped payout.</p>${table(["Clip / user label", "Kills", "Original", "A reference", "B reference", "C credit"], d.clips.map((c) => "<tr>" + cells([c.id + " · " + c.judgment, fmt(c.kills), fmt(c.original), fmt(c.A), fmt(c.B), fmt(c.credit)]) + "</tr>").join(""))}<p>Clips 05 and 08 are labelled Wasteful yet their one-kill shots receive 70 and 90 points under B, versus 20 and 80 originally. Clip 09 is Productive but its focal shot has no credited kill, so these formulas pay it nothing. Clips 03 and 10 have no selected shot; a dash does not mean withholding is worth zero defense value.</p><p class="callout">These disagreements expose a proxy problem, not a mislabeled player. They do not support ranking runs from sparse clip labels. Small aiming improvements and actual save value require controlled play with changed inputs, beyond this fixed-event experiment.</p></section>
<section><h2>Parameter and cohort sensitivity</h2><p>Ranges were specified before this calculation; no setting was tuned to these results. Six whole runs (numbers divisible by four) form a sensitivity holdout, with 20 in the reference subset. All had already been inspected earlier: this is not an unseen validation set. Build summaries below are descriptive and do not establish cross-build effects.</p>${table(["Setting", "Point change", "Gain / lose", "Better-defense pairs", "Cap saturated"], d.summaries.map((s) => "<tr>" + cells([s.id + " · " + setting(s), ((100 * s.delta) / s.original).toFixed(1) + "%", s.gain + " / " + s.lose, s.pairs.higher + " / 12", s.saturated === null ? "—" : s.saturated + " / 194"]) + "</tr>").join(""))}<div id="sensitivity"></div><p>Leaving one run out never changes the direction of the pooled point reduction at any setting. That proves the scale change is broad; it does not prove a quality improvement. Strict-pair counts remain dependent and change when a shared recording is removed.</p></section>
<section><h2>Decision boundary</h2><p>A directly addresses the automated-combo incentive but preserves risk from empty manual shots. B removes streak risk but rewards unnecessary kills and splitting larger groups. C bounds the contribution premium and avoids a pure last-hit rule, yet often saturates and has no observed assist benefit here.</p><p><strong>Do not choose a replacement from these recordings.</strong> The next design decision is which skilled choices and execution should earn more when both runs survive. Timing, aim, prioritization and resource use are candidate dimensions to clarify, not validated metrics. More manual contribution or fewer asset losses alone cannot settle that question. Part Six and late-wave experiments have not begun.</p></section>
<section><h2>Verification and reproduction</h2><p>${d.checks.original.toLocaleString("en-US")} original points reconcile across 26 runs, 168 completed waves and 26 terminal waves; all 3,394 accepted shots remain represented, including four terminal unresolved lineages. Prior baseline and instrumented summaries match. Rescoring imports no gameplay code and only consumes observations.</p><p>Independent Python agrees on ${proof.waveVariantChecks} wave/formula calculations, ${proof.runRankChecks} run rank checks and all 12 strict pair differences. Eleven rule cases exercise assist attribution, bonuses/debits, multi-kills, caps, terminal shots and wave boundaries. SHA-256 digests confirm all ${proof.unchangedInputs} consumed input files stayed unchanged. This reuses the earlier replay proofs; it does not claim candidate simulation replay validation.</p><p><a href="scoring-rescoring-method.md">Exact formulas, caveats and reproduction</a> · <a href="scoring-progression-results.html">Part four evidence</a> · <a href="README.md">Report series</a></p><p class="muted">Anonymous report only. Raw recordings, labels with shot IDs, input digests and verification artifacts stay in the ignored local study directory. No gameplay edits, new captures, deployment, commit or push.</p></section>
<script id="data" type="application/json">${JSON.stringify({ ...d, clips: undefined }).replace(/</g, "\\u003c")}</script><script>
const D=JSON.parse(document.getElementById('data').textContent),$=id=>document.getElementById(id),fmt=n=>n.toLocaleString('en-US',{maximumFractionDigits:1}),signed=n=>(n>0?'+':'')+fmt(n),td=xs=>'<tr>'+xs.map(x=>'<td>'+x+'</td>').join('')+'</tr>',rank=(xs,value)=>1+xs.filter(x=>x>value).length+(xs.filter(x=>x===value).length-1)/2;
function render(){const id=$('variant').value,scope=$('scope').value,s=D.summaries.find(s=>s.id===id);let rows=scope==='all'?D.runs.map(r=>({label:r.label,original:r.gross,candidate:r.scores[id].gross})):D.throughWave.find(w=>String(w.wave)===scope).rows.map(r=>({...r,candidate:r.scores[id]}));
$('selection').textContent=rows.length+' runs · '+s.id+' · '+(scope==='all'?'final totals':'through completed wave '+scope)+' · pooled change '+signed(rows.reduce((a,r)=>a+r.candidate-r.original,0))+' points';const max=Math.max(...rows.map(r=>Math.abs(r.candidate-r.original)));
$('runs').innerHTML=rows.map(r=>{const change=rank(rows.map(x=>x.original),r.original)-rank(rows.map(x=>x.candidate),r.candidate);return td([r.label,fmt(r.original),fmt(r.candidate),signed(r.candidate-r.original)+'<span class="bar" style="width:'+Math.abs(r.candidate-r.original)/Math.max(1,max)*140+'px"></span>','<span class="'+(change>0?'up':change<0?'down':'')+'">'+signed(change)+'</span>']);}).join('');
$('pairs').innerHTML=D.pairs.map(p=>td([p.better,p.worse,p.wave,signed(p.original),signed(p.scores[id])])).join('');$('pairSummary').textContent=s.pairs.higher+' favor better protection; '+s.pairs.tied+' tie; '+s.pairs.lower+' favor the worse-protected recording.';
const r=D.runs.find(r=>r.label===$('run').value);$('runContext').textContent=r.label+' · '+r.build+' · '+r.subset+' subset · '+(100*r.automationBaseShare).toFixed(1)+'% of kill base from non-manual sources · original net '+fmt(r.original)+' → candidate net '+fmt(r.scores[id].net);$('waves').innerHTML=r.waves.map(w=>td([w.wave+(w.terminal?' · terminal':''),fmt(w.gross),fmt(w.base),fmt(w.bonuses),fmt(w.scores[id].premium),fmt(w.debits),fmt(w.scores[id].net)])).join('');
const cohorts=[...s.subsets.map(x=>({...x,label:x.subset})),...s.builds.map(x=>({...x,label:x.build}))];$('sensitivity').innerHTML='<h3>Selected setting: '+id+'</h3><div class="scroll"><table><thead><tr><th>Cohort</th><th>Runs</th><th>Point change</th><th>Rank correlation</th></tr></thead><tbody>'+cohorts.map(c=>td([c.label,c.n,(100*c.delta/c.original).toFixed(1)+'%',c.rankCorrelation===null?'not estimable':c.rankCorrelation.toFixed(3)])).join('')+'</tbody></table></div><p>Leave-one-run-out pooled change: '+s.looPercentRange.map(n=>n.toFixed(1)+'%').join(' to ')+'. Pair higher-count range after omitting each run: '+Math.min(...s.pairLeaveOneRunOut.map(p=>p.higher))+'–'+Math.max(...s.pairLeaveOneRunOut.map(p=>p.higher))+'; remaining pair count '+Math.min(...s.pairLeaveOneRunOut.map(p=>p.n))+'–'+Math.max(...s.pairLeaveOneRunOut.map(p=>p.n))+'.</p>';
}for(const id of ['variant','scope','run'])$(id).addEventListener('change',render);render();
</script></main></body></html>`;
writeFileSync(
  "docs/gameplay analysis Sep 2026/scoring-rescoring-results.html",
  await format(html, { ...(await resolveConfig(".prettierrc")), parser: "html" }),
);
console.log("Wrote anonymous Part Five report.");
