// Creates a frozen mock game state for the graphics editor preview
import { CANVAS_W, CANVAS_H, GROUND_Y, COL, createScenicBuildings } from "./game-logic.js";
import type { GameState } from "./types";

export function createEditorScene(): GameState {
  const allBuildings = createScenicBuildings();

  return {
    _debugMode: false,
    _showColliders: false,
    _editorMode: true,
    state: "playing",
    score: 12450,
    wave: 3,
    stats: { missileKills: 12, droneKills: 5, shotsFired: 28 },
    ammo: [8, 11, 5],
    launcherHP: [1, 1, 1],
    missiles: [
      {
        x: 300,
        y: 300,
        vx: 0.5,
        vy: 1.8,
        alive: true,
        trail: Array.from({ length: 10 }, (_, i) => ({ x: 300 - i * 0.3, y: 300 - i * 1.8 })),
      },
      {
        x: 650,
        y: 500,
        vx: -0.3,
        vy: 2.0,
        alive: true,
        trail: Array.from({ length: 10 }, (_, i) => ({ x: 650 + i * 0.2, y: 500 - i * 2.0 })),
      },
      {
        x: 150,
        y: 200,
        vx: 0.8,
        vy: 1.5,
        alive: true,
        trail: Array.from({ length: 10 }, (_, i) => ({ x: 150 - i * 0.5, y: 200 - i * 1.5 })),
        type: "mirv",
        health: 3,
      },
      {
        x: 480,
        y: 700,
        vx: -0.2,
        vy: 1.6,
        alive: true,
        trail: Array.from({ length: 10 }, (_, i) => ({ x: 480 + i * 0.1, y: 700 - i * 1.6 })),
      },
    ],
    drones: [
      {
        x: 100,
        y: 400,
        vx: 1.5,
        vy: 0.3,
        alive: true,
        subtype: "shahed136",
        health: 2,
        heading: 0.2,
        trail: Array.from({ length: 8 }, (_, i) => ({ x: 100 - i * 1.5, y: 400 - i * 0.3 })),
        pathIndex: 0,
        waypoints: [],
      },
      {
        x: 750,
        y: 250,
        vx: -1.2,
        vy: 0.5,
        alive: true,
        subtype: "shahed238",
        health: 3,
        heading: -0.3,
        trail: Array.from({ length: 8 }, (_, i) => ({ x: 750 + i * 1.2, y: 250 - i * 0.5 })),
        pathIndex: 0,
        waypoints: [],
      },
      {
        x: 450,
        y: 650,
        vx: 1.0,
        vy: 0.4,
        alive: true,
        subtype: "shahed136",
        health: 2,
        heading: 0.1,
        trail: Array.from({ length: 8 }, (_, i) => ({ x: 450 - i * 1.0, y: 650 - i * 0.4 })),
        pathIndex: 0,
        waypoints: [],
      },
    ],
    interceptors: [
      {
        x: 200,
        y: 900,
        vx: 1,
        vy: -2.5,
        alive: true,
        heading: -1.2,
        trail: Array.from({ length: 15 }, (_, i) => ({ x: 200 - i * 0.7, y: 900 + i * 1.8 })),
        targetX: 300,
        targetY: 300,
      },
      {
        x: 600,
        y: 1000,
        vx: -0.5,
        vy: -3,
        alive: true,
        heading: -1.7,
        trail: Array.from({ length: 12 }, (_, i) => ({ x: 600 + i * 0.4, y: 1000 + i * 2.2 })),
        targetX: 650,
        targetY: 500,
      },
    ],
    explosions: [
      // Threat explosion (growing) — upper area
      {
        id: 1,
        x: 350,
        y: 350,
        radius: 35,
        maxRadius: 55,
        growing: true,
        alpha: 0.9,
        color: COL.explosion,
        playerCaused: false,
        harmless: false,
        chain: false,
        ringRadius: 20,
        ringAlpha: 0.6,
      },
      // Interceptor detonation (fresh) — mid area
      {
        id: 2,
        x: 700,
        y: 550,
        radius: 74,
        maxRadius: 74,
        growing: false,
        alpha: 1.0,
        color: "#44ffaa",
        playerCaused: true,
        harmless: false,
        chain: false,
        ringRadius: 0,
        ringAlpha: 1,
      },
      // Chain explosion (fading) — between upper and mid
      {
        id: 3,
        x: 200,
        y: 200,
        radius: 40,
        maxRadius: 45,
        growing: false,
        alpha: 0.4,
        color: "#ff4400",
        playerCaused: false,
        harmless: false,
        chain: true,
        ringRadius: 60,
        ringAlpha: 0.1,
      },
    ],
    particles: [
      // Dots (around threat explosion)
      ...Array.from({ length: 8 }, () => ({
        x: 350 + (Math.random() - 0.5) * 60,
        y: 350 + (Math.random() - 0.5) * 60,
        vx: (Math.random() - 0.5) * 4,
        vy: (Math.random() - 0.5) * 4,
        life: 20 + Math.random() * 30,
        maxLife: 50,
        color: Math.random() > 0.5 ? "#ffcc00" : "#ff6600",
        size: 1 + Math.random() * 3,
      })),
      // Debris (around chain explosion)
      ...Array.from({ length: 6 }, () => ({
        x: 200 + (Math.random() - 0.5) * 80,
        y: 200 + (Math.random() - 0.5) * 60,
        vx: (Math.random() - 0.5) * 3,
        vy: -1 + Math.random() * 2,
        life: 30 + Math.random() * 30,
        maxLife: 60,
        color: Math.random() > 0.4 ? "#666" : "#994400",
        size: 2 + Math.random() * 2,
        type: "debris",
        angle: Math.random() * Math.PI * 2,
        spin: (Math.random() - 0.5) * 0.25,
        gravity: 0.15,
        w: 2 + Math.random() * 2,
        h: 2 + Math.random() * 3,
        drag: 0.96,
      })),
      // Sparks (around interceptor explosion)
      ...Array.from({ length: 8 }, () => ({
        x: 700 + (Math.random() - 0.5) * 40,
        y: 550 + (Math.random() - 0.5) * 40,
        vx: (Math.random() - 0.5) * 8,
        vy: (Math.random() - 0.5) * 8,
        life: 10 + Math.random() * 15,
        maxLife: 25,
        color: Math.random() > 0.5 ? "#fff" : "#ffee88",
        size: 0.5 + Math.random() * 1,
        type: "spark",
        drag: 0.93,
        gravity: 0.02,
      })),
    ],
    planes: [],
    buildings: allBuildings,
    burjAlive: true,
    burjHealth: 5,
    stars: Array.from({ length: 200 }, () => ({
      x: Math.random() * CANVAS_W,
      y: -CANVAS_H * 1.2 + Math.random() * CANVAS_H * 1.8,
      size: 0.5 + Math.random() * 1.5,
      twinkle: Math.random() * Math.PI * 2,
    })),
    planeTimer: 0,
    planeInterval: 800,
    waveComplete: false,
    crosshairX: -100,
    crosshairY: -100,
    time: 100,
    shakeTimer: 0,
    shakeIntensity: 0,
    upgrades: {
      wildHornets: 0,
      roadrunner: 0,
      flare: 0,
      ironBeam: 0,
      phalanx: 0,
      patriot: 0,
      burjRepair: 0,
      launcherKit: 0,
      emp: 0,
    },
    defenseSites: [],
    hornets: [],
    roadrunners: [],
    laserBeams: [],
    phalanxBullets: [],
    patriotMissiles: [],
    flares: [],
    hornetTimer: 360,
    roadrunnerTimer: 480,
    ironBeamTimer: 360,
    phalanxTimer: 5,
    patriotTimer: 480,
    flareTimer: 240,
    nextFlareId: 1,
    empCharge: 0,
    empChargeMax: 0,
    empReady: false,
    empRings: [],
    multiKillToast: null,
    launcherFireTick: [0, 0, 0],
    _replayTick: 100,
    commander: { style: "balanced", history: [] },
    schedule: [],
    scheduleIdx: 0,
    waveTick: 0,
    concurrentCap: 10,
    waveTactics: [],
  } as unknown as GameState;
}
