// Graphics editor parameter definitions
// Each parameter maps to a hardcoded value in the Pixi renderer or game logic.

export const PARAM_GROUPS = [
  {
    name: "Explosions",
    params: [
      {
        key: "explosion.lightIntensity",
        label: "Light Intensity",
        type: "range",
        min: 0,
        max: 0.5,
        step: 0.01,
        default: 0.13,
      },
      {
        key: "explosion.lightRadiusMul",
        label: "Light Radius (x explosion)",
        type: "range",
        min: 1,
        max: 12,
        step: 0.1,
        default: 7.2,
      },
      {
        key: "explosion.splashIntensity",
        label: "Splash Alpha",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.34,
      },
      {
        key: "explosion.splashRadiusMul",
        label: "Splash Radius (x explosion)",
        type: "range",
        min: 1,
        max: 10,
        step: 0.1,
        default: 3.8,
      },
      {
        key: "explosion.ringFadeRate",
        label: "Ring Fade Rate",
        type: "range",
        min: 0.05,
        max: 1,
        step: 0.01,
        default: 0.25,
      },
      {
        key: "explosion.ringExpandRate",
        label: "Ring Expand Rate",
        type: "range",
        min: 2,
        max: 30,
        step: 1,
        default: 14,
      },
      {
        key: "explosion.fireballAlpha",
        label: "Fireball Alpha",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.54,
      },
      {
        key: "explosion.fireballRadiusMul",
        label: "Fireball Radius (x explosion)",
        type: "range",
        min: 0,
        max: 6,
        step: 0.05,
        default: 0.95,
      },
      {
        key: "explosion.coreAlpha",
        label: "Core Alpha",
        type: "range",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.59,
      },
      {
        key: "explosion.coreRadiusMul",
        label: "Core Radius (x explosion)",
        type: "range",
        min: 0,
        max: 3,
        step: 0.01,
        default: 0.26,
      },
      {
        key: "explosion.fadeRate",
        label: "Fireball Fade Rate",
        type: "range",
        min: 0.01,
        max: 0.2,
        step: 0.005,
        default: 0.085,
      },
    ],
  },
  {
    name: "Particles",
    params: [
      {
        key: "particle.dotCountLight",
        label: "Dot Count (light)",
        type: "range",
        min: 1,
        max: 20,
        step: 1,
        default: 7,
      },
      {
        key: "particle.dotCountHeavy",
        label: "Dot Count (heavy)",
        type: "range",
        min: 1,
        max: 30,
        step: 1,
        default: 10,
      },
      { key: "particle.debrisCount", label: "Debris Count", type: "range", min: 0, max: 30, step: 1, default: 26 },
      {
        key: "particle.sparkCountLight",
        label: "Spark Count (light)",
        type: "range",
        min: 1,
        max: 25,
        step: 1,
        default: 19,
      },
      {
        key: "particle.sparkCountHeavy",
        label: "Spark Count (heavy)",
        type: "range",
        min: 1,
        max: 30,
        step: 1,
        default: 25,
      },
      {
        key: "particle.debrisGravity",
        label: "Debris Gravity",
        type: "range",
        min: 0,
        max: 0.5,
        step: 0.01,
        default: 0.3,
      },
      {
        key: "particle.debrisDrag",
        label: "Debris Drag",
        type: "range",
        min: 0.85,
        max: 1,
        step: 0.005,
        default: 0.96,
      },
      { key: "particle.sparkDrag", label: "Spark Drag", type: "range", min: 0.85, max: 1, step: 0.005, default: 0.93 },
    ],
  },
  {
    name: "Burj",
    params: [
      { key: "burj.coronaAlpha", label: "Corona Alpha", type: "range", min: 0, max: 0.5, step: 0.01, default: 0.1 },
      { key: "burj.uplightAlpha", label: "Uplight Alpha", type: "range", min: 0, max: 0.3, step: 0.005, default: 0.08 },
      {
        key: "burj.outlineGlowRadius",
        label: "Outline Glow Radius",
        type: "range",
        min: 5,
        max: 60,
        step: 1,
        default: 25,
      },
      {
        key: "burj.basePoolRadius",
        label: "Base Pool Radius",
        type: "range",
        min: 30,
        max: 300,
        step: 5,
        default: 150,
      },
      {
        key: "burj.basePoolAlpha",
        label: "Base Pool Alpha",
        type: "range",
        min: 0,
        max: 0.3,
        step: 0.005,
        default: 0.08,
      },
    ],
  },
  {
    name: "Burj Fire",
    params: [
      { key: "burjFire.flameRate", label: "Flame Rate", type: "range", min: 0, max: 8, step: 0.1, default: 0.9 },
      { key: "burjFire.flameLife", label: "Flame Life", type: "range", min: 6, max: 60, step: 1, default: 51 },
      { key: "burjFire.flameSize", label: "Flame Size", type: "range", min: 2, max: 28, step: 0.5, default: 7.5 },
      { key: "burjFire.emberRate", label: "Ember Rate", type: "range", min: 0, max: 5, step: 0.05, default: 1.25 },
      { key: "burjFire.emberLife", label: "Ember Life", type: "range", min: 12, max: 120, step: 2, default: 100 },
      { key: "burjFire.emberSize", label: "Ember Size", type: "range", min: 0.6, max: 8, step: 0.1, default: 2.5 },
      { key: "burjFire.smokeRate", label: "Smoke Rate", type: "range", min: 0, max: 4, step: 0.05, default: 0.75 },
      { key: "burjFire.smokeLife", label: "Smoke Life", type: "range", min: 60, max: 420, step: 5, default: 155 },
      { key: "burjFire.smokeSize", label: "Smoke Size", type: "range", min: 2, max: 32, step: 0.5, default: 7.5 },
      { key: "burjFire.smokeRise", label: "Smoke Rise", type: "range", min: 0.1, max: 2, step: 0.05, default: 1.35 },
      {
        key: "burjFire.smokeDrift",
        label: "Smoke Drift Right",
        type: "range",
        min: 0,
        max: 0.8,
        step: 0.01,
        default: 0.44,
      },
      { key: "burjFire.smokeBase", label: "Smoke Base", type: "range", min: 0, max: 1.5, step: 0.02, default: 0.35 },
      {
        key: "burjFire.smokeYOffset",
        label: "Smoke Y Offset",
        type: "range",
        min: -90,
        max: 90,
        step: 1,
        default: 17,
      },
      {
        key: "burjFire.hotspotSpread",
        label: "Hotspot Spread",
        type: "range",
        min: 0,
        max: 0.95,
        step: 0.02,
        default: 0.62,
      },
      {
        key: "burjFire.hitFlashFlameMul",
        label: "Hit Flame Kick",
        type: "range",
        min: 1,
        max: 6,
        step: 0.1,
        default: 3.4,
      },
      {
        key: "burjFire.hitFlashSmokeMul",
        label: "Hit Smoke Kick",
        type: "range",
        min: 1,
        max: 5,
        step: 0.1,
        default: 2.4,
      },
      {
        key: "burjFire.flameAlphaMul",
        label: "Flame Alpha Mul",
        type: "range",
        min: 0.2,
        max: 1.6,
        step: 0.02,
        default: 0.98,
      },
      {
        key: "burjFire.emberAlphaMul",
        label: "Ember Alpha Mul",
        type: "range",
        min: 0.2,
        max: 1.6,
        step: 0.02,
        default: 0.95,
      },
      {
        key: "burjFire.smokeAlphaMul",
        label: "Smoke Alpha Mul",
        type: "range",
        min: 0.1,
        max: 1.2,
        step: 0.02,
        default: 0.26,
      },
      {
        key: "burjFire.smokeGrowth",
        label: "Smoke Growth",
        type: "range",
        min: 0.4,
        max: 4.5,
        step: 0.05,
        default: 2,
      },
      {
        key: "burjFire.flameSizeMul",
        label: "Flame Size Mul",
        type: "range",
        min: 0.3,
        max: 2.0,
        step: 0.05,
        default: 0.75,
      },
      {
        key: "burjFire.smokeSizeMul",
        label: "Smoke Size Mul",
        type: "range",
        min: 0.3,
        max: 2.0,
        step: 0.05,
        default: 1.3,
      },
      {
        key: "burjFire.smokeDamageMul",
        label: "Smoke Rate vs Damage",
        type: "range",
        min: 0,
        max: 4,
        step: 0.05,
        default: 2.4,
      },
      {
        key: "burjFire.smokeRiseDamageBoost",
        label: "Smoke Rise vs Damage",
        type: "range",
        min: 0,
        max: 1.5,
        step: 0.05,
        default: 0.5,
      },
      {
        key: "burjFire.flicker",
        label: "Flame Flicker",
        type: "range",
        min: 0,
        max: 0.5,
        step: 0.01,
        default: 0,
      },
    ],
  },
  {
    name: "Sky",
    params: [
      { key: "sky.nebulaOpacity", label: "Nebula Opacity", type: "range", min: 0, max: 1, step: 0.05, default: 0.4 },
      {
        key: "sky.starTwinkleSpeed",
        label: "Star Twinkle Speed",
        type: "range",
        min: 0.005,
        max: 0.1,
        step: 0.005,
        default: 0.02,
      },
      { key: "sky.vignetteAlpha", label: "Vignette Alpha", type: "range", min: 0, max: 0.8, step: 0.02, default: 0.42 },
    ],
  },
  {
    name: "Glow",
    params: [
      { key: "glow.scale", label: "Glow Scale", type: "range", min: 0, max: 1.5, step: 0.05, default: 0.45 },
      { key: "glow.enabled", label: "Glow Enabled", type: "checkbox", default: true },
    ],
  },
  {
    name: "Upgrade Ranges",
    params: [
      {
        key: "upgrade.ironBeamRange",
        label: "Iron Beam Range",
        type: "range",
        min: 50,
        max: 600,
        step: 5,
        default: 368,
      },
      { key: "upgrade.phalanxRange", label: "Phalanx Range", type: "range", min: 30, max: 400, step: 5, default: 160 },
      { key: "upgrade.empRange", label: "EMP Radius", type: "range", min: 100, max: 900, step: 10, default: 715 },
      {
        key: "upgrade.flareActivationRange",
        label: "Flare Activation Range",
        type: "range",
        min: 50,
        max: 900,
        step: 5,
        default: 320,
      },
    ],
  },
];

// Build a flat map of defaults
export function getDefaults(): Record<string, number | boolean | string> {
  const defaults: Record<string, number | boolean | string> = {};
  for (const group of PARAM_GROUPS) {
    for (const p of group.params) {
      defaults[p.key] = p.default;
    }
  }
  return defaults;
}
